[QuoteServer]
Domain = "quoteserver"
Port = 4441

[WebServer]
Domain = "webserver"
Port = 8080

[Redis]
Domain = "redis"
Port = 6379

[Database]
Username = "postgres"
Password = "mysecretpass"
Database = "quote"
Domain = "database"
Port = 5432
SSLMode = "disable"

[LoadBalancer]
Domain = "loadbalancer"
port = 5555

[Trigger]
Domain = "trigger"
port = 12345
