[QuoteServer]
Domain = "quoteserver"
Port = 8080

[WebServer]
Domain = "webserver"
Port = 8080

[Redis]
Domain = "redis"
Port = 6379

[Database]
Username = "postgres"
Password = "mysecretpass"
Database = "quote"
Domain = "postgres"
Port = 5432