version: '3'

services:
  webserver:
    image: 127.0.0.1:5000/webserver
    depends_on:
      - redis
    build:
      args:
        - buildpath=webserver
      dockerfile: go-build/Dockerfile
      context: .
    extra_hosts:
      - "quoteserver:172.18.0.1"
    networks:
      default:
        aliases:
          - webserver
    command: /app/bin/webserver
    ports:
     - "8000:8080"
  redis:
    image: redis:4.0.8-alpine
    ports:
     - "6379:6379"
  loadbalancer:
    image: 127.0.0.1:5000/loadbalancer
    build:
      args:
        - buildpath=load-balance
      dockerfile: go/Dockerfile
      context: .
    networks:
      default:
        aliases:
          - loadbalancer
    ports:
      - 5555:5555
