version: '3'

services:
  webserver:
    depends_on:
      - redis
      - database
    build:
      args:
        - buildpath=webserver
      dockerfile: go-build/Dockerfile
      context: .
    extra_hosts:
      - "quoteserver:192.168.1.148"
    networks:
      default:
        aliases:
          - webserver
    command: /app/bin/webserver
    ports:
     - "8000:8080"

  redis:
    image: redis:4.0.8-alpine
    ports:
     - "6379:6379"

  database:
    image: postgres:10.3-alpine
    ports:
     - "5432:5432"
    environment:
      restart: always
    build:
      context: database
      dockerfile: Dockerfile

